services:
  reddit-bot:
    image: python:3.9-slim
    pull_policy: always
    container_name: reddit-rss-bot
    restart: unless-stopped
    volumes:
      - ./bot_script:/app
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    env_file:
      - .env
    # Installs dependencies and runs python in unbuffered mode (-u)
    command: >
      sh -c "pip install -r requirements.txt && python -u main.py"
